### ISSUE TITLE
[Feature] Specify custom endpoint for CLI

### ISSUE THREAD

**Issue by 3onyc** [grimborg/gitgitlab#1]
Currently there's no way to specify a self-hosted GitLab install, perhaps add this in the form of an `~/.gitgitlab.rc` file or something similar?

**Comment by grimborg** [comment]
Thanks for the request. I'll add it.

**Comment by dmke** [comment]
+1, but I'd prefer a section in my `.gitconfig`.

**Comment by 3onyc** [comment]
+1 @dmke 

And also per repository in `.git/config` perhaps?

**Comment by dmke** [comment]
[Of course](https://www.kernel.org/pub/software/scm/git/docs/git-config.html#FILES) :smile:

**Comment by grimborg** [comment]
Added! See [Using a custom Gitlab server](https://github.com/grimborg/gitgitlab#using-a-custom-gitlab-server) on the documentation.

I don't have my own Gitlab server to test on; could you test and see if it works for you?

Thanks!

**Comment by 3onyc** [comment]
Creating projects succeeds. However from what I can tell you're storing 1 token in the keyring rather than a token per API endpoint?

**Comment by grimborg** [comment]
You're right. Fixed it. Thanks!
