### ISSUE TITLE
gitgitlab uses wrong url

### ISSUE THREAD

**Issue by ricwein** [grimborg/gitgitlab#5]
Hi,
my gitgitlab won't work with another gitlab-server than gitlab.com.
I changed the gitlab->url in my .gitconfig as supposed, but when I try an `git lab list` or `git lab auth` it still trys to connect to gitlab.com.
![screen shot 2014-06-04 at 15 47 21](https://cloud.githubusercontent.com/assets/870354/3174167/f8b17020-ebee-11e3-98e8-cbf3ba3c1c44.png)

Now the funnny part: when I try to run the binary directly from its Folder (`/usr/local/bin/git-lab`) it works! Well, at least to the Point where it fails with another error... but it looks at the right server-url!
![screen shot 2014-06-04 at 15 48 25](https://cloud.githubusercontent.com/assets/870354/3174172/0d88b2e2-ebef-11e3-8779-39bc9e747f31.png)

I've already checked for the used `git` and `git-lab` command-link, but it's correct:
![screen shot 2014-06-04 at 15 50 39](https://cloud.githubusercontent.com/assets/870354/3174206/51ec6bb8-ebef-11e3-8486-878307e664be.png)

Any idea what causes this problem?
Im working on OS X Maverick 10.9.3 with git 2.0.0 from homebrew.

**Comment by 3onyc** [comment]
You need to specify the protocol so try changing the url to `http://ricwein.com`

**Comment by ricwein** [comment]
Oh sorry, I've forgot to mention that I also tried this. Same result. It apparently doesn't matter if i set it to `ricwein.com`, `http://ricwein.com` or even `https://ricwein.com`.

**Comment by grimborg** [comment]
Thanks for the bug report! This bug is related to how gitgitlab fetches the settings and it seems to only happen if you run git lab outside of a git repository. As a temporary workaround, could you run git lab inside of a git repository?

I'll investigate a fix.

**Comment by ricwein** [comment]
Oh right, it really only happens if gitgitlab runs outside of a git-repo.
Except for the `git lab auth` function, which opens `gitlab.com`, even if I'm in a git-folder. Because of this I'm not able to set a correct auth-token right now.
But I'm glad to hear, that you're working on it.

_Edit_: I deleted the auth-token from my keychain, and after adding it again via `git lab list` etc. it works for now. But the `git lab auth` still opens gitlab.com.

**Comment by ricwein** [comment]
After updating gitgitlab it seems like something went wrong with your fix. It fails at `Can't connect to GitLab server (None/api/v3)` now, independent to the current directory. The entry in `.gitconfig` is still correct.

**Comment by grimborg** [comment]
Fixed both problems. Please upgrade and check if it works for you.

**Comment by ricwein** [comment]
Ah perfect. With your second fix everything works again.
You're a genius! Thank you very much!

**Comment by grimborg** [comment]
Awesome! Thanks a lot for your feedback, it really helped!
